version: '3.8'

services:
  emmet-server:
    build: ./
    ports:
      - 65000:65000
    depends_on:
      postgresql:
        condition: service_healthy
    links:
      - postgresql

  postgresql:
      restart: always
      build: ./postgresql/
      volumes:
        - /var/lib/postgresql/data
      ports:
        - 5431:5432
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
      environment:
        POSTGRES_DB: emmet
        POSTGRES_PASSWORD: 12345678
