
server:
  host: "localhost"
  port: ":65000"

database:
  uri: "host=localhost dbname=emmet sslmode=disable user=postgres password=12345678 port=5432"

token:
  secret_key: "test_secret_key"
  public_key: "test_public_key"
  salt: "salt"

logger:
  log_level: "debug"